Initial version
HelloKitty322/minenot1 pull request #1
Opened 2024-10-24 09:52 UTC by HelloKitty322

2024-10-24 09:54 UTC, yadotrof commented on BSFGbot2.py
> +async def main():
привет

2024-10-24 13:13 UTC, yadotrof requested changes
ну шо, пробуй

2024-10-24 13:13 UTC, yadotrof commented on professions.csv
кажется это дубликат, такой же есть  в handlers
давай удалим

2024-10-24 13:13 UTC, yadotrof commented on keyboards/for_begin_keyboard.py
> +from aiogram.types import ReplyKeyboardMarkup, InlineKeyboardMarkup
InlineKeyboardMarkup не используется

2024-10-24 13:13 UTC, yadotrof commented on keyboards/for_begin_keyboard.py
> +from aiogram.utils.keyboard import InlineKeyboardBuilder, ReplyKeyboardBuilder
InlineKeyboardBuilder не используется

2024-10-24 13:13 UTC, yadotrof commented on keyboards/for_begin_keyboard.py
> +    races = ['Империя', 'Альянс', 'Доминион', 'Орда', 'Союз', 'Легион', 'Белатто']
логичнее заранее считать рассы из файла и взять множество
так твоя программа будет независима от списка расс

2024-10-24 13:13 UTC, yadotrof commented on BSFGbot2.py
обычно запускаемый файл называют main.py
чтобы человек сразу мог понять что тут надо запустить

2024-10-24 13:13 UTC, yadotrof commented on config.py
> +TOKEN = '7522794727:AAGuH8HUroz6CjYyu8IKrImuTQf_VYCtktI'
плохая затея выкладывать токен в гит. особенно в паблик репу
давай просто пустую строку закомитим.
и запомни: если ключ попал хоть в один коммит -- он скомпрометирован, и останется в истории гита, даже если ты сделаешь еще 1 коммит.
это значит что нужно его сменить

2024-10-24 13:13 UTC, yadotrof commented on handlers/answers.py
> +Races = ['империя', 'альянс', 'доминион', 'орда', 'союз', 'легион', 'белатто']
рассы тоже лучше считать из файла как профессии

2024-10-24 13:13 UTC, yadotrof commented on handlers/answers.py
> +Classes = {'чародеи': 'debaff', 'тяжелые воины': 'hdd', 'легкие воины': 'ldd', 'маги': 'mage',
а зачем этот мапинг? может просто использовать как есть? чародеи, и тд
и соответственно в csv  поменять

2024-10-24 13:13 UTC, yadotrof commented on handlers/answers.py
> +    await message.answer('Этот бот выдает ссылка на интересующий вас раздел из базы знаний BSFG')
```suggestion
    await message.answer('Этот бот выдает ссылкy на интересующий вас раздел из базы знаний BSFG')

```

2024-10-24 13:13 UTC, yadotrof commented on handlers/answers.py
> +@router.message(lambda message: message.text and message.text.lower() in professions_list)
а почему ты не используешь F.text.lower()
или на нем in  не работает?

2024-10-24 13:13 UTC, yadotrof commented on handlers/ttest.py
заебись тест, но кажется можно удалить

2024-10-24 13:13 UTC, yadotrof commented on handlers/ttest.py
> +print(user.__dict__)
видишь значек 
![image](https://github.com/user-attachments/assets/797bfa68-2e44-496f-98d5-756e45a1cb85)
он значит что нет пустой строки в конце, а нужна

2024-10-24 13:13 UTC, yadotrof commented on keyboards/answer_inline_keybords.py
> +def classes(needed_class) -> ReplyKeyboardMarkup:
не очень удобно что в answers.py есть переменнаая Classes
кстати КОНСТАНТЫ пишут капсом, а с большой буквы Классы

2024-10-24 13:13 UTC, yadotrof commented on keyboards/answer_inline_keybords.py
> +    with open('professions.csv', 'r', encoding='UTF-8') as file:
думаешь есть смысл каждый раз читать файл?
а если у тебя будет толпа пользователей? на каждое письмо файл будет читаться
давай вынесем за функцию

2024-10-24 13:13 UTC, yadotrof commented on keyboards/for_begin_keyboard.py
> +    data = ['Чародеи', 'Тяжелые воины', 'Легкие воины', 'Маги', 'Мастера Войны', 'Рыцари', 'Убийцы', 'Стрелки',
ну во, а тут еще раз классы объеявлены, но уже не диктом

2024-10-24 13:13 UTC, yadotrof commented on keyboards/for_classes_keyboard.py
> +    with open('professions.csv', 'r', encoding='UTF-8') as file:
это тоже можно считать не в функции

2024-10-24 13:13 UTC, yadotrof commented on keyboards/for_classes_keyboard.py
> +    with open('professions.csv', 'r', encoding='UTF-8') as file:
и тут тоже.
вытащи работу с файлом в отдельный модуль.
в модуле прочти файл, сделай себе дикты, константы и тд, а потом просто импортируй этот модуль и используй

2024-10-24 13:13 UTC, yadotrof commented on keyboards/for_classes_keyboard.py
> +def classes_list():
оппа, еще раз классы, только теперь это зачем-то функция, хотя думаю ты и сам видишь что это константа

2024-10-24 13:13 UTC, yadotrof commented on keyboards/for_start_keyboard.py
> +from aiogram.types import ReplyKeyboardMarkup, InlineKeyboardMarkup
опять неиспользуемые импорты

2024-10-24 16:12 UTC, HelloKitty322 commented on handlers/answers.py
> +Classes = {'чародеи': 'debaff', 'тяжелые воины': 'hdd', 'легкие воины': 'ldd', 'маги': 'mage',
Я просто копировал часть кода страницы, закинул его в строку и из строки сделал csv, прост в коде классы на английском  указаны и я не стал мучаться, разве что функцию подправил

2024-10-24 16:21 UTC, HelloKitty322 commented on handlers/answers.py
> +@router.message(lambda message: message.text and message.text.lower() in professions_list)
Ну тут у меня плохие познания в aiogram, я не понял что такой за класс F, и решил как в telebote в анонимную функцию вписать message, и раз уж на то пошло мне показалось, что название аргумента в анонимной функции должно совпадать с названиями в параметрах))) Кароч я шото накрутил

2024-10-24 16:23 UTC, HelloKitty322 commented on handlers/answers.py
> +@router.message(lambda message: message.text and message.text.lower() in professions_list)
Тип если я заменю на F.text.lower(), то мне в аргумент функции вставить просто F?

2024-10-24 16:40 UTC, HelloKitty322 commented on handlers/answers.py
> +@router.message(lambda message: message.text and message.text.lower() in professions_list)
А, ну так и можно было сделать, теперь буду знать))))

2024-10-24 18:22 UTC, HelloKitty322 commented on handlers/answers.py
> +Races = ['империя', 'альянс', 'доминион', 'орда', 'союз', 'легион', 'белатто']
'рассы' -> 'расы'

2024-10-25 12:39 UTC, yadotrof requested changes

2024-10-25 12:39 UTC, yadotrof commented on .DS_Store
почитай про .gitignore
и удали этот файл

2024-10-25 12:39 UTC, yadotrof commented on collection.py
> +    file_list = list(reader)
список файлов?
может просто data?

2024-10-25 12:39 UTC, yadotrof commented on collection.py
> +    all_professions = list(map(lambda x: x['Название профессии'].lower(), file_list))
научись компрехеншены писать :) мы тут не js  пишем

all_professions = [i['Название профессии'].lower() for i in data]

2024-10-25 12:39 UTC, yadotrof commented on collection.py
> +    pics_list = list(reader)
а ты не хочешь сразу словарь собрать профессия-ссылка?
искать же не придется потом

2024-10-25 12:39 UTC, yadotrof commented on keyboards/for_classes_keyboard.py
> +def pic(name_pic) -> str:
был бы словарь не нужно было бы это писать

2024-10-25 12:39 UTC, yadotrof commented on keyboards/answer_inline_keybords.py
> +    needed_professions = list(filter(lambda x: x['Класс'] == CLASSES[needed_class.lower()], file_list))
давай сделаем функцию get_jobs_by_class в модуле collection
а тут просто вызовем

2024-10-25 12:39 UTC, yadotrof commented on keyboards/for_professions_keyboard.py
> +    needed_profession = list(filter(lambda x: x['Раса'] == race, file_list))
а это тоже можно сделать в collection get_jobs_by_race

2024-10-25 12:42 UTC, yadotrof commented on keyboards/for_classes_keyboard.py
> +def profession_link(arg) -> InlineKeyboardMarkup:
job_link_by_name

2024-10-25 12:42 UTC, yadotrof commented on keyboards/for_classes_keyboard.py
> +def classes_link(arg) -> InlineKeyboardMarkup:
job_link_by_name_and_race ?

2024-10-25 12:45 UTC, HelloKitty322 commented on collection.py
> +    file_list = list(reader)
Я прост любитель написать где угодно data, мне так удобнее будет, особенно если в будущем добавлю еще файл какой-нибудь и расширю бота. Но если надо - то поменяю

2024-10-25 12:49 UTC, HelloKitty322 commented on keyboards/for_classes_keyboard.py
> +def pic(name_pic) -> str:
Так этих 3 строк у меня нет в коде, откуда они тут

2024-10-25 12:50 UTC, yadotrof requested changes

2024-10-25 12:50 UTC, yadotrof commented on keyboards/answer_inline_keybords.py
> +def classes(needed_class) -> ReplyKeyboardMarkup:
jobs_by_class_keyboard

2024-10-25 12:50 UTC, yadotrof commented on keyboards/for_begin_keyboard.py
> +def begin_buttons_professions() -> ReplyKeyboardMarkup:
races_keyboard

2024-10-25 12:50 UTC, yadotrof commented on keyboards/for_begin_keyboard.py
> +def begin_buttons() -> ReplyKeyboardMarkup:
search_menu_keyboard

2024-10-25 12:50 UTC, yadotrof commented on keyboards/for_begin_keyboard.py
> +def begin_buttons_classes() -> ReplyKeyboardMarkup:
classes_keyboard

2024-10-25 12:50 UTC, yadotrof commented on keyboards/for_classes_keyboard.py
> +def off_site_link():
site_link_keyboard

2024-10-25 12:50 UTC, yadotrof commented on keyboards/for_classes_keyboard.py
> +def off_db_link():
db_link_keyboard

2024-10-25 12:50 UTC, yadotrof commented on keyboards/for_professions_keyboard.py
> +def professions(race) -> ReplyKeyboardMarkup:
jobs_by_race_keyboard()

2024-10-25 12:50 UTC, yadotrof commented on keyboards/for_start_keyboard.py
> +def start_buttons() -> ReplyKeyboardMarkup:
main_menu_keyboard

2024-10-25 12:50 UTC, yadotrof commented on keyboards/for_start_keyboard.py
> +def start_buttons() -> ReplyKeyboardMarkup:
на самом деле можешь все клавы положить в 1 файл
их пока мало, так что будет норм, просто сначала главное меню, потом ссылки, потом выбор как искать, потом все остальное

2024-10-25 12:53 UTC, HelloKitty322 commented on keyboards/for_start_keyboard.py
> +def start_buttons() -> ReplyKeyboardMarkup:
То есть мне все файлы из папки Keyboard совместить в один?

2024-10-25 12:57 UTC, yadotrof commented on collection.py
> +    file_list = list(reader)
ну напиши jobs_data
если планируешь где-то использовать

разные модули в реальном мире могут писать разные люди не вдаваясь в подробности 
и вот если кто-то посреди проекта увидит file_list то жестко охуеет потому что не понятно что за список файлов

я предлоджил data как что-то нейтральное что за пределами модуля использоваться не будет

2024-10-25 12:58 UTC, yadotrof commented on keyboards/for_classes_keyboard.py
> +def pic(name_pic) -> str:
я про функцию pic()

2024-10-25 12:58 UTC, yadotrof commented on keyboards/for_start_keyboard.py
> +def start_buttons() -> ReplyKeyboardMarkup:
ну да, там же максимум пара сот срок, а суть одна

2024-10-29 17:14 UTC, HelloKitty322 commented
Блин, про камприхеншины забыл(

2024-10-29 17:15 UTC, HelloKitty322 commented
И конфигурация хай так лежит уже, все равно его все знают, потом поменяю

2024-10-29 17:17 UTC, yadotrof commented on collection.py
> +        pics_list.setdefault(i['Название профессии'], i['Ссылка на картинку'])
list ? :)

2024-10-29 17:17 UTC, yadotrof commented on config.py
> +TOKEN = '7522794727:AAGuH8HUroz6CjYyu8IKrImuTQf_VYCtktI'
хехехе

2024-10-29 17:20 UTC, HelloKitty322 commented
Отбой, все норм вроде кроме конфига, проверяй

2024-10-29 17:20 UTC, HelloKitty322 commented
Ладно, увидел твои коменты, отбой снова, ща все переделаю

2024-10-29 17:21 UTC, yadotrof commented on handlers/answers.py
> +from minenot1.keyboards.keyboards import *
вообще можно, но обычно в реальности люди не любят такой импорт, потому что не понятно откуда какое имя
либо уже перечислять все что нужно в импорте либо модуль импортнуть
1)
```py
from module import a,b,c
a()
```
2)
```py
from .import module
module.a()
```
и давай из папки вытащим
git mv keyboards/keyboards.py keyboards.py

2024-10-29 17:22 UTC, yadotrof commented on handlers/answers.py
> +    await message.answer_photo(photo=pics_list[message.text], reply_markup=job_link_by_name_keyboard(message.text))
тут бы хорошо обработать ситуацию когда у тебя картинки не хватило, но в целом похуй

2024-10-29 17:23 UTC, yadotrof commented on keyboards/keyboards.py
> +def main_menu_keyboard() -> ReplyKeyboardMarkup:
ты же тоже снизу-вверх слева-направо читаешь?

а поч тогда главное меню которое юзер видит в начале стоит в конце файла?

2024-10-29 17:41 UTC, yadotrof approved these changes

2024-10-29 17:43 UTC, merged